#!/bin/sh

cd $(dirname $0)

nasm -f elf32 native.s
#nasm -f bin native.s
cp native.o ../../bin/lonos.native.o

nasm -f bin EnableExecutionProtection.s -o EnableExecutionProtection.o
cp EnableExecutionProtection.o ../../bin/lonos.EnableExecutionProtection.o

nasm -f bin InterruptReturn.s -o InterruptReturn.o
cp InterruptReturn.o ../../bin/lonos.InterruptReturn.o

nasm -f bin InterruptReturn2.s -o InterruptReturn2.o
cp InterruptReturn2.o ../../bin/lonos.InterruptReturn2.o

nasm -f bin LoadTaskRegister.s -o LoadTaskRegister.o
cp LoadTaskRegister.o ../../bin/lonos.LoadTaskRegister.o

