#!/bin/bash

cd $(dirname $0)
source env/default

function configure {
	case $1 in
		all)
			configure patch apply
			;;

		external)
			git clone --recursive git@github.com:lonos-project/lonos-tools.git tools
			;;

		patch)
			patch ${@:2}
			;;

		mosa)
			external/MOSA-Project/Source/Compile.sh
			;;

		*)
			echo $"Usage: lonosctl configure {all|patch|mosa}"
			exit 1
	esac
}

function patch {
	case $1 in
		apply)
			patches/apply
			;;

		revert)
			patches/apply --reverse
			;;

		*)
			echo $"Usage: lonosctl configure patch {apply|revert}"
			exit 1
	esac
}

function build {
	case $1 in
		all)
			build builder
			build assembly
			build native
			build disk
			;;

		builder)
			(cd src && msbuild lonos.build.sln /p:Configuration=Release)
			;;

		assembly)
			(cd src && msbuild lonos.kernel.sln /p:Configuration=Debug)
			;;

		native)
			src/lonos.native/build
			;;

		disk)
			(cd bin && mono ./lonos.build.exe)
			create_efi_disk
			create_grub_hybrid_disk
			;;

		*)
			echo $"Usage: lonosctl build {all|builder|assembly|native|disk}"
			exit 1
	esac
}

function run {
	case $1 in
		bochs)
			_bochs ${@:2}
			;;

		qemu)
			_qemu ${@:2}
			;;

		*)
			echo $"Usage: lonosctl run {qemu|bochs}"
			exit 1
	esac
}

function _bochs {
	case $1 in
		x86)
			arch=x86
			;;

		x64)
			arch=x64
			;;

		*)
			echo $"Usage: lonosctl run qemu {x86|x64|host}"
			exit 1
	esac

	bochsrc="${LONOS_PROJDIR}/conf/bochs-${arch}.bxrc"
	bochs -f ${bochsrc} -rc "${LONOS_PROJDIR}/conf/bochs.rc"
}

function _qemu {
	disk=${LONOS_OSDIR}/lonos.kernel.core.img
	
	case $1 in
		x86)
			arch=x86
			qemubin=qemu-system-i386
			cpu=qemu32,+sse4.1
			bios="-L /usr/share/seabios"
			;;

		x86-grub-vbe)
			arch=x86
			qemubin=qemu-system-i386
			cpu=qemu32,+sse4.1
			bios="-L /usr/share/seabios"

			disk=${LONOS_OSDIR}/lonos.kernel.core.x86-grub-hybrid.disk.img
			;;

		x86-efi)
			arch=x86
			qemubin=qemu-system-i386
			cpu=qemu32,+sse4.1
			bios="-bios ${LONOS_PROJDIR}/tools/ovmf-ia32/OVMF-pure-efi.fd"

			disk=${LONOS_OSDIR}/lonos.kernel.core.x86-efi.disk.img
			;;

		x64)
			arch=x64
			qemubin=qemu-system-x86_64
			cpu=qemu64
			bios="-L /usr/share/seabios"
			;;

		host)
			arch=x64
			qemubin=qemu-system-x86_64
			cpu=host
			kvmargs=-enable-kvm
			bios="-L /usr/share/seabios"
			;;

		*)
			echo $"Usage: lonosctl run qemu {x86|x86-efi|x86-grub-vbe|x64|host}"
			exit 1
	esac

	echo ${qemubin} ${bios} ${kvmargs} -cpu ${cpu} -hda $disk -serial file:${LONOS_PROJDIR}/logs/kernel.log -d pcall,cpu_reset,guest_errors -D ${LONOS_PROJDIR}/logs/emulator.log
	     ${qemubin} ${bios} ${kvmargs} -cpu ${cpu} -hda $disk -serial file:${LONOS_PROJDIR}/logs/kernel.log -d pcall,cpu_reset,guest_errors -D ${LONOS_PROJDIR}/logs/emulator.log
}

#function create_chroot {
	#wget ${alpine_mirror}/latest-stable/main/x86_64/apk-tools-static-${alpine_version}.apk
	#tar -xzf apk-tools-static-*.apk	
	#wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.9.0/alpine-chroot-install \
    #&& echo 'e5dfbbdc0c4b3363b99334510976c86bfa6cb251  alpine-chroot-install' | sha1sum -c \
    #|| exit 1
	#chmod +x alpine-chroot-install
#}

function create_efi_disk {
	disk=${LONOS_OSDIR}/lonos.kernel.core.x86-efi.disk.img
	size=20440 #kb
	let "block=((size * 1024) / (512 * 16 * 16)) - 1"
	echo $block
	dd if=/dev/zero of=$disk bs=1k count=$size
	mformat -i $disk -h 16 -t 16 -s $block ::

	mcopy -i $disk -s $LONOS_TOOLSDIR/grub-efi-x86/efi ::/
	mcopy -i $disk -s $LONOS_TOOLSDIR/grub-efi-x86/boot ::/
	mcopy -i $disk -s $LONOS_TOOLSDIR/grub-efi-x86/NvVars ::/
	mcopy -i $disk -s $LONOS_TOOLSDIR/grub-efi-x86/.disk ::/
	mcopy -i $disk -s $LONOS_OSDIR/lonos.kernel.core.bin ::/lonos.bin
}

function create_grub_hybrid_disk {
	disk=${LONOS_OSDIR}/lonos.kernel.core.x86-grub-hybrid.disk.img
	isodir=$LONOS_PROJDIR/tmp/iso-grub-hybrid
	mkdir -p $isodir;
	cp $LONOS_OSDIR/lonos.kernel.core.bin $isodir/lonos.bin
	mkdir -p $isodir/boot/grub
	cp $LONOS_TOOLSDIR/grub-efi-x86/boot/grub/grub.cfg $isodir/boot/grub
	grub-mkrescue -o $disk $isodir
}

function logs {
	case $1 in
		kernel)
			less +F "${LONOS_PROJDIR}/logs/kernel.log"
			;;

		emulator)
			less +F "${LONOS_PROJDIR}/logs/emulator.log"
			;;

		*)
			echo $"Usage: lonosctl logs {kernel|emulator}"
			exit 1
	esac
}

case $1 in
	configure)
		configure ${@:2}
		;;

	build)
		build ${@:2}
		;;

	run)
		run ${@:2}
		;;

	logs)
		logs ${@:2}
		;;

	f1)
		create_efi_disk ${@:2}
		#create_chroot
		;;

	*)
		echo $"Usage: lonosctl {configure|build|run|logs}"
		exit 1
esac

