#!/bin/bash

cd $(dirname $0)
source env/default

function configure {
	case $1 in
		all)
			configure patch apply
			;;

		patch)
			patch ${@:2}
			;;

		mosa)
			external/MOSA-Project/Source/Compile.sh
			;;

		*)
			echo $"Usage: lonosctl configure {all|patch|mosa}"
			exit 1
	esac
}

function patch {
	case $1 in
		apply)
			patches/apply
			;;

		revert)
			patches/apply --reverse
			;;

		*)
			echo $"Usage: lonosctl configure patch {apply|revert}"
			exit 1
	esac
}

function build {
	case $1 in
		all)
			build builder
			build assembly
			build native
			build disk
			;;

		builder)
			(cd src && msbuild lonos.build.sln /p:Configuration=Release)
			;;

		assembly)
			(cd src && msbuild lonos.kernel.sln /p:Configuration=Debug)
			;;

		native)
			src/lonos.native/build
			;;

		disk)
			(cd bin && mono ./lonos.build.exe)
			;;

		*)
			echo $"Usage: lonosctl build {all|builder|assembly|native|disk}"
			exit 1
	esac
}

function run {
	case $1 in
		bochs)
			_bochs ${@:2}
			;;

		qemu)
			_qemu ${@:2}
			;;

		*)
			echo $"Usage: lonosctl run {qemu|bochs}"
			exit 1
	esac
}

function _bochs {
	case $1 in
		x86)
			arch=x86
			;;

		x64)
			arch=x64
			;;

		*)
			echo $"Usage: lonosctl run qemu {x86|x64|host}"
			exit 1
	esac

	bochsrc="${LONOS_PROJDIR}/conf/bochs-${arch}.bxrc"
	bochs -f ${bochsrc} -rc "${LONOS_PROJDIR}/conf/bochs.rc"
}

function _qemu {
	case $1 in
		x86)
			arch=x86
			qemubin=qemu-system-i386
			cpu=qemu32,+sse4.1
			;;

		x64)
			arch=x64
			qemubin=qemu-system-x86_64
			cpu=qemu64
			;;

		host)
			arch=x64
			qemubin=qemu-system-x86_64
			cpu=host
			kvmargs=-enable-kvm
			;;

		*)
			echo $"Usage: lonosctl run qemu {x86|x64|host}"
			exit 1
	esac

	${qemubin} -L /usr/share/seabios ${kvmargs} -cpu ${cpu} -hda ${LONOS_OSDIR}/lonos.kernel.core.img -serial file:${LONOS_PROJDIR}/logs/kernel.log -d pcall,cpu_reset,guest_errors -D ${LONOS_PROJDIR}/logs/emulator.log
}

function logs {
	case $1 in
		kernel)
			less +F "${LONOS_PROJDIR}/logs/kernel.log"
			;;

		emulator)
			less +F "${LONOS_PROJDIR}/logs/emulator.log"
			;;

		*)
			echo $"Usage: lonosctl logs {kernel|emulator}"
			exit 1
	esac
}

case $1 in
	configure)
		configure ${@:2}
		;;

	build)
		build ${@:2}
		;;

	run)
		run ${@:2}
		;;

	logs)
		logs ${@:2}
		;;

	*)
		echo $"Usage: lonosctl {configure|build|run|logs}"
		exit 1
esac

