#!/bin/sh

cd $(dirname $0)

ARCH=x86
mkdir -p ../../bin/$ARCH

nasm -f elf32 Native.s -o Native.o
#nasm -f bin native.s
cp Native.o ../../bin/$ARCH/Abanu.Native.o

nasm -f bin EnableExecutionProtection.s -o EnableExecutionProtection.o
cp EnableExecutionProtection.o ../../bin/$ARCH/Abanu.EnableExecutionProtection.o

nasm -f bin InterruptReturn.s -o InterruptReturn.o
cp InterruptReturn.o ../../bin/$ARCH/Abanu.InterruptReturn.o

nasm -f bin CpuCyclesSinceBoot.s -o CpuCyclesSinceBoot.o
cp CpuCyclesSinceBoot.o ../../bin/$ARCH/Abanu.CpuCyclesSinceBoot.o

nasm -f bin ReadFlags.s -o ReadFlags.o
cp ReadFlags.o ../../bin/$ARCH/Abanu.ReadFlags.o

nasm -f bin GetThreadLocalStorage.s -o GetThreadLocalStorage.o
cp GetThreadLocalStorage.o ../../bin/$ARCH/Abanu.GetThreadLocalStorage.o

nasm -f bin SetThreadLocalStorage.s -o SetThreadLocalStorage.o
cp SetThreadLocalStorage.o ../../bin/$ARCH/Abanu.SetThreadLocalStorage.o

nasm -f bin LoadTaskRegister.s -o LoadTaskRegister.o
cp LoadTaskRegister.o ../../bin/$ARCH/Abanu.LoadTaskRegister.o

nasm -f bin DebugFunction1.s -o DebugFunction1.o
cp DebugFunction1.o ../../bin/$ARCH/Abanu.DebugFunction1.o

nasm -f bin SysCall.s -o SysCall.o
cp SysCall.o ../../bin/$ARCH/Abanu.SysCall.o
