#!/bin/sh

cd $(dirname $0)

ARCH=x86
mkdir -p ../../bin/$ARCH

nasm -f elf32 native.s -o native.o
#nasm -f bin native.s
cp native.o ../../bin/$ARCH/lonos.native.o

nasm -f bin EnableExecutionProtection.s -o EnableExecutionProtection.o
cp EnableExecutionProtection.o ../../bin/$ARCH/lonos.EnableExecutionProtection.o

nasm -f bin InterruptReturn.s -o InterruptReturn.o
cp InterruptReturn.o ../../bin/$ARCH/lonos.InterruptReturn.o

nasm -f bin LoadTaskRegister.s -o LoadTaskRegister.o
cp LoadTaskRegister.o ../../bin/$ARCH/lonos.LoadTaskRegister.o

nasm -f bin DebugFunction1.s -o DebugFunction1.o
cp DebugFunction1.o ../../bin/$ARCH/lonos.DebugFunction1.o

nasm -f bin app.HelloKernel.s -o app.HelloKernel.o
cp app.HelloKernel.o ../../bin/$ARCH/app.HelloKernel.o
