#!/bin/bash

export ABANU_PROJDIR=$(
cd $(dirname "$BASH_SOURCE")
cd .. 
echo $(cmd.exe /C "echo|set /p=%CD%")
)

nuget="cmd.exe /C external\\MOSA-Project\\Tools\\nuget\\nuget.exe"

PATH=/mnt/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/MSBuild/Current/Bin:$PATH
PATH=/mnt/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Professional/MSBuild/Current/Bin:$PATH
PATH=/mnt/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Community/MSBuild/Current/Bin:$PATH
PATH=/mnt/d/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/MSBuild/Current/Bin:$PATH
msbuild=MSBuild.exe
ABANU_BUILD="cmd.exe /C Abanu.Tools.Build.exe"

QEMU_X86="cmd.exe /C ${ABANU_PROJDIR}\\external\\MOSA-Project\\Tools\\qemu\\qemu-system-i386.exe"
QEMU_X64="cmd.exe /C ${ABANU_PROJDIR}\\external\\MOSA-Project\\Tools\\qemu\\qemu-system-x86_64.exe"
#QEMU_X86=$QEMU_X64

source $(dirname "$BASH_SOURCE")/shared

function __platform_abspath {
	echo $(wslpath -m $(realpath $1))
}
