#!/bin/bash

#echo detected $ABANU_PROJDIR

export ABANU_ARCH=x86
export ABANU_EXE=${ABANU_PROJDIR}/bin/Abanu.OS.Core.${ABANU_ARCH}.exe
export ABANU_BOOTLOADER_EXE=${ABANU_PROJDIR}/bin/Abanu.OS.Loader.${ABANU_ARCH}.exe
export ABANU_OSDIR=${ABANU_PROJDIR}/os
export ABANU_NATIVE_FILES=${ABANU_PROJDIR}/bin/${ABANU_ARCH}/Abanu.Native.o
export ABANU_LOGDIR=${ABANU_PROJDIR}/logs
export ABANU_TMPDIR=${ABANU_PROJDIR}/tmp
export ABANU_ISODIR=${ABANU_TMPDIR}/iso
export ABANU_TOOLSDIR=${ABANU_PROJDIR}/tools

source $(dirname "$BASH_SOURCE")/local
if [ -f ~/.config/abanu/env ] ; then
	source ~/.config/abanu/env
fi

#export chroot_dir=${ABANU_PROJDIR}/chroot
#export alpine_mirror=http://mirror.clarkson.edu/alpine/
#export alpine_version=3.8

