#!/bin/bash

export ABANU_PROJDIR=$(
cd $(dirname "$BASH_SOURCE")
cd .. 
pwd
)

nuget="mono ${ABANU_PROJDIR}/external/MOSA-Project/Tools/nuget/nuget.exe"
msbuild=msbuild
ABANU_BUILD="mono -O=all abanu.tools.build.exe"
QEMU_X86=qemu-system-i386
QEMU_X64=qemu-system-x86_64

source $(dirname "$BASH_SOURCE")/shared 

function __platform_abspath {
	echo $(realpath $1)
}
